I'm sorry, but an uncaught exception occurred.

While running game code:
  File "script.rpy", line 155, in script
    "Our main character, who is moving in to his new apartment, is excited to start fresh and make new neighbor friends."
  File "renpy/common/000window.rpy", line 122, in _window_auto_callback
    _window_show(auto=True)
  File "renpy/common/000window.rpy", line 70, in _window_show
    renpy.with_statement(trans)
OSError: Couldn't find file 'audio/backgroundMusic.mp3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "script.rpy", line 155, in script
    "Our main character, who is moving in to his new apartment, is excited to start fresh and make new neighbor friends."
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/ast.py", line 2557, in execute
    Say.execute(self)
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/ast.py", line 585, in execute
    statement_name("say")
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/ast.py", line 52, in statement_name
    i(name)
  File "renpy/common/000window.rpy", line 122, in _window_auto_callback
    _window_show(auto=True)
  File "renpy/common/000window.rpy", line 70, in _window_show
    renpy.with_statement(trans)
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/exports.py", line 1781, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/display/core.py", line 1548, in do_with
    return self.interact(trans_pause=True,
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/display/core.py", line 2165, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/display/core.py", line 3022, in interact_core
    renpy.audio.audio.periodic()
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/audio/audio.py", line 1205, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/audio/audio.py", line 1183, in periodic_thread_main
    periodic_pass()
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/audio/audio.py", line 1125, in periodic_pass
    c.periodic()
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/audio/audio.py", line 534, in periodic
    topf = load(filename)
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/audio/audio.py", line 72, in load
    rv = renpy.loader.load(fn, directory="audio")
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/loader.py", line 672, in load
    raise IOError("Couldn't find file '%s'." % name)
OSError: Couldn't find file 'audio/backgroundMusic.mp3'.

macOS-14.3.1-arm64-arm-64bit arm64
Ren'Py 8.2.1.24030407
novel 1.0
Sat May 11 22:55:06 2024
