I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 82, in script
    call screen scene_1
  File "renpy/common/000statements.rpy", line 671, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "game/script.rpy", line 50, in execute
    screen safe_puzzle:
  File "game/script.rpy", line 50, in execute
    screen safe_puzzle:
  File "game/script.rpy", line 52, in execute
    image "images/dial-shadow.png" align(0.48, 0.5) alpha 0.3 at half_size
  File "game/script.rpy", line 52, in keywords
    image "images/dial-shadow.png" align(0.48, 0.5) alpha 0.3 at half_size
  File "game/script.rpy", line 52, in <module>
    image "images/dial-shadow.png" align(0.48, 0.5) alpha 0.3 at half_size
NameError: name 'half_size' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 82, in script
    call screen scene_1
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/ast.py", line 1968, in execute
    self.call("execute")
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/ast.py", line 1950, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/statements.py", line 349, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 671, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/exports.py", line 3413, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/display/core.py", line 2165, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/display/core.py", line 2687, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/display/displayable.py", line 431, in visit_all
    d.visit_all(callback, seen)
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/display/displayable.py", line 431, in visit_all
    d.visit_all(callback, seen)
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/display/displayable.py", line 431, in visit_all
    d.visit_all(callback, seen)
  [Previous line repeated 2 more times]
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/display/screen.py", line 480, in visit_all
    callback(self)
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/display/core.py", line 2687, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/display/screen.py", line 491, in per_interact
    self.update()
  File "/Volumes/renpy-8.2.1-sdk/renpy-8.2.1-sdk/renpy/display/screen.py", line 697, in update
    self.screen.function(**self.scope)
  File "game/script.rpy", line 50, in execute
    screen safe_puzzle:
  File "game/script.rpy", line 50, in execute
    screen safe_puzzle:
  File "game/script.rpy", line 52, in execute
    image "images/dial-shadow.png" align(0.48, 0.5) alpha 0.3 at half_size
  File "game/script.rpy", line 52, in keywords
    image "images/dial-shadow.png" align(0.48, 0.5) alpha 0.3 at half_size
  File "game/script.rpy", line 52, in <module>
    image "images/dial-shadow.png" align(0.48, 0.5) alpha 0.3 at half_size
NameError: name 'half_size' is not defined

macOS-14.3-arm64-arm-64bit arm64
Ren'Py 8.2.1.24030407
safedoor 1.0
Mon May  6 10:12:59 2024
